---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: nginx-default
    image: leandelivery/docker-systemd:ubuntu-20.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
  - name: nginx-custom
    image: leandelivery/docker-systemd:ubuntu-20.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
  - name: nginx-disabled
    image: leandelivery/docker-systemd:ubuntu-20.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  inventory:
    host_vars:
      nginx-custom:
        nginx_keep_default_configs: true
        nginx_stable_repo: false
        nginx_logrotate_interval: weekly
        nginx_logrotate_backlog_size: 5
      nginx-disabled:
        nginx_systemd_setup: false
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: ubuntu2004
verifier:
  name: testinfra
