---
# tasks file for roles/nginx-proxy logroate config

- name: logrotate | configure main file
  become: true
  template:
    backup: false
    dest: /etc/logrotate.d/nginx
    src: logrotated-nginx.j2
