---
- name: Import a key for nginx
  ansible.builtin.rpm_key:
    state: present
    key:  https://nginx.org/keys/nginx_signing.key

- name: system packages | setup upstream nginx stable repo
  become: true
   ansible.builtin.dnf:
    update_cache: true
    name: "https://nginx.org/packages/centos/9/x86_64/RPMS/nginx-1.24.0-1.el9.ngx.x86_64.rpm"
    state: present
  when: nginx_stable_repo

- name: system packages | setup upstream nginx mainline repo
  become: true
  copy:
    src: nginx-mainline.repo
    dest: /etc/yum.repos.d/nginx-mainline.repo
    mode: 0644
  when: not nginx_stable_repo

- name: system packages | check if epel is installed
  stat:
    path: '/etc/yum.repos.d/epel.repo'
  register: epel_repo

- name: system packages | install nginx
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: >-
      nginx
    state: present

# example_ssl.conf is in some distro versions but not upstream, disable it
# just in case
- name: nginx | remove default config
  become: true
  copy:
    content: "# This file is intentionally blank (Ansible)"
    dest: /etc/nginx/conf.d/{{ item }}
    mode: 0644
  with_items:
    - example_ssl.conf
    - default.conf
  when: not (nginx_keep_default_configs | default(False))
  notify:
    - restart nginx
